<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Source\Zelanthus.API\Zelanthus.API.csproj" />
    <ProjectReference Include="..\..\Source\Zelanthus.Prompting\Zelanthus.Prompting.csproj" />
    <ProjectReference Include="..\..\Source\Zelanthus.Llm.Clients.Abstractions\Zelanthus.Llm.Clients.Abstractions.csproj" />
    <ProjectReference Include="..\..\Source\Zelanthus.Llm.Clients.Gemini\Zelanthus.Llm.Clients.Gemini.csproj" />
    <ProjectReference Include="..\..\Source\Zelanthus.StoryEngine.Domain\Zelanthus.StoryEngine.Domain.csproj" />
    <ProjectReference Include="..\..\Source\Zelanthus.StoryEngine.Application\Zelanthus.StoryEngine.Application.csproj" />
    <ProjectReference Include="..\..\Source\Zelanthus.StoryEngine.Infrastructure\Zelanthus.StoryEngine.Infrastructure.csproj" />
  </ItemGroup>

</Project>